export const OPENSPIN = "OPENSPIN"
export const CLOSESPIN = "CLOSESPIN"
export const MODIFYIFAJAX = "MODIFYIFAJAX"
export const PREVPATH = "PREVPATH"
export const NPROGRESSSTATE = "NPROGRESSSTATE"


export const FETCH_LOGIN_BEGIN = 'FETCH_LOGIN_BEGIN';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const BEGIN_LOGINOUT = 'BEGIN_LOGINOUT';
export const SUCCESS_LOGINOUT = 'SUCCESS_LOGINOUT';
export const FAILURE_LOGINOUT = 'FAILURE_LOGINOUT';


